### PR TITLE
feat: add transistor config schema file

### PR DESCRIPTION
**Pull request by francinelucca**
Adds a schema file for transistor config with npm and jsx scope typings. 

Note for @jdharvey-ibm I made some constraints here that I felt made sense like:

- require top-level "collect" and "projectId" keys
- require at least 1 scope to be defined
- require at least 1 property to be defined per scope
- require at least 1 attribute if `allowedAtrributeNames` is defined
- require at least 1 string value if `allowedAttributeStringValues` is define

#### Changelog

**New**

- Added transistor config schema file: src/schemas/transistor-config.schema.json
- Added dedicated per-scope schema files

#### Testing / reviewing

test out adding and removing keys from test.yml or creating your own file

#### TODO: remove test.yml file

### CODE REVIEW

**Review by mattrosno — COMMENTED** [review]
I like how we are using a published package for the Carbon Platform schema to validate YAML config files. E.g.

```yml
# yaml-language-server: $schema=https://unpkg.com/@carbon-platform/schemas@v1/carbon-resources.schema.json
designKits:
  carbon-white-sketch:
    name: Sketch white theme
```

Do we want the schema to live in its own package?

Or, if we want to publish it as part of this package (e.g. `@ibm/transistor-js`), what would we need to do to expose the schema as part of the top level package so an instrumented code package could use unpkg to use a versioned schema file? E.g.:

```yml
# yaml-language-server: $schema=https://unpkg.com/@ibm/transistor-js@v1/transistor-config.schema.json
collect:
    npm:
        dependencies:
```

Said differently, how could we achieve this:

`https://unpkg.com/@ibm/transistor-js@v1/transistor-config.schema.json`

Instead of depending on the internal directory structure:

`https://unpkg.com/@ibm/transistor-js@v1/src/schemas/transistor-config.schema.json`?

**Review by mattrosno — COMMENTED** [review]
With top-level `collect` and `projectId` keys, we're dependent on the YAML file names like `transistor.yml` to find and parse the config.

I'm wondering if we should nest everything inside a top-level `transistor` key, e.g.:

```yml
transistor:
  collect:
    npm:
      dependencies:
  projectId: "1234"
```

Would this enable potential future config and indexing consolidation? Let's say the future has one `ibm.yml` config to both instrument for metrics and index for website catalogs:

```yml
assets:
  accordion:
    name: Accordion
  aspect-ratio:
    name: Aspect ratio
libraries:
  carbon-react:
    name: Carbon React
    assets:
      $ref: '#/assets'
transistor:
  collect:
    npm:
      dependencies:
  projectId: "1234"
```

Or... if `collect` and `projectId` are unique and have no foreseen conflicts with Carbon Platform and InnerSource indexing... then we're good and we don't need the top level `transistor` key?

CC @jdharvey-ibm

**Review by mattrosno — COMMENTED** [review]
Just some description prose cleanup.

**Review by jharvey10 — CHANGES_REQUESTED** [review]

**Review by mattrosno — APPROVED** [review]
Comments in Schema.ts LGTM.

**Review by jharvey10 — CHANGES_REQUESTED** [review]

**Review by jharvey10 — APPROVED** [review]

**Pull request merged**
